import React, { useEffect, useState } from 'react';
import { getAlerts, updateAlert } from '../api/alertApi';
import { ALERT_STATUSES } from '../utils/constants';
import RiskBadge from '../components/RiskBadge.jsx';
import Loader from '../components/Loader.jsx';
import { formatDate } from '../utils/formatDate';

export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  async function load() {
    setLoading(true);
    setError('');
    try {
      const data = await getAlerts();
      setAlerts(data);
    } catch (err) {
      setError('Failed to load alerts');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function handleStatusChange(id, status) {
    try {
      await updateAlert(id, { status });
      load();
    } catch (err) {
      setError('Failed to update alert');
    }
  }

  return (
    <div className="page">
      <div className="page-header">
        <h2>Alerts</h2>
        <p className="muted">All risk alerts generated by the engine.</p>
      </div>

      {error && <div className="error-banner">{error}</div>}

      <div className="card">
        {loading ? (
          <Loader />
        ) : alerts.length === 0 ? (
          <div className="muted">No alerts found</div>
        ) : (
          <div className="table-wrap">
            <table className="table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>User</th>
                  <th>Type</th>
                  <th>Risk</th>
                  <th>Message</th>
                  <th>Status</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((a) => (
                  <tr key={a.id}>
                    <td>{a.id}</td>
                    <td>{a.user_id}</td>
                    <td>{a.alert_type}</td>
                    <td><RiskBadge level={a.risk_level} /></td>
                    <td className="td-message">{a.message}</td>
                    <td>
                      <select
                        value={a.status}
                        onChange={(e) => handleStatusChange(a.id, e.target.value)}
                      >
                        {ALERT_STATUSES.map((s) => (
                          <option key={s} value={s}>{s}</option>
                        ))}
                      </select>
                    </td>
                    <td>{formatDate(a.created_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
